In [1]:
import numpy as np

In [ ]:
import array

In [ ]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [ ]:
np.array([1,2,3,4,"rahulkumar"])

array(['1', '2', '3', '4', 'rahul'], dtype='<U21')

In [ ]:
np.array([1,2,3,4,5,6.0])

array([1., 2., 3., 4., 5., 6.])

In [6]:
np.array([[1,3],[3,4],[6,7,6]])

/var/folders/z3/3z1nzc5j04bfv5b365gtfgm40000gn/T/ipykernel_24909/2425907191.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,6]])


array([list([1, 3]), list([3, 4]), list([6, 7, 6])], dtype=object)

In [7]:
np.array([[[1,2],[4,1]],[[3,1],[2,6]]])

array([[[1, 2],
        [4, 1]],

       [[3, 1],
        [2, 6]]])

In [8]:
np.array([1,2,3], ndmin = 3)  # 3D representation

array([[[1, 2, 3]]])

In [9]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
np.array([(1,2),(4,2)])

array([[1, 2],
       [4, 2]])

In [11]:
arr=np.array([(1,2),(4,2)],dtype=[("a",'<i4'),("b",'<i8')])

In [12]:
arr

array([(1, 2), (4, 2)], dtype=[('a', '<i4'), ('b', '<i8')])

In [13]:
arr[0]

(1, 2)

In [14]:
arr[0][0]

1

In [15]:
type(arr[0][0])

numpy.int32

In [16]:
type(arr[0][1])

numpy.int64

In [17]:
arr = np.array([[1,3],[3,4]])

In [18]:
arr

array([[1, 3],
       [3, 4]])

In [19]:
arr[0][0]

1

In [20]:
type(arr[0][0])

numpy.int64

In [21]:
arr[0]

array([1, 3])

In [22]:
mat=np.mat(arr)

In [23]:
l=[3,4,5,56,3,7]

In [24]:
l

[3, 4, 5, 56, 3, 7]

In [25]:
np.array(l)

array([ 3,  4,  5, 56,  3,  7])

In [26]:
np.asarray(l)

array([ 3,  4,  5, 56,  3,  7])

In [27]:
np.asanyarray(l)

array([ 3,  4,  5, 56,  3,  7])

In [28]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [29]:
np.array(mat)

array([[1, 3],
       [3, 4]])

In [30]:
issubclass(np.matrix,np.ndarray)

True

In [31]:
arr

array([[1, 3],
       [3, 4]])

In [32]:
a=arr #shallow copy

In [33]:
b=np.copy(arr)  #Deep copy

In [34]:
arr[0][0]=67

In [35]:
arr

array([[67,  3],
       [ 3,  4]])

In [36]:
a

array([[67,  3],
       [ 3,  4]])

In [37]:
b

array([[1, 3],
       [3, 4]])

In [38]:
arr[-1]

array([3, 4])

In [39]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [40]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [41]:
np.fromfunction(lambda i , j :i*j,(4,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [42]:
np.fromfunction(lambda i, j: i/j,(3,3))

/var/folders/z3/3z1nzc5j04bfv5b365gtfgm40000gn/T/ipykernel_24909/1707235418.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j: i/j,(3,3))
/var/folders/z3/3z1nzc5j04bfv5b365gtfgm40000gn/T/ipykernel_24909/1707235418.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j: i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [43]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [44]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7fd5717bf510>

In [45]:
def test(x):
    yield x

In [46]:
test(5)

<generator object test at 0x7fd5717bf5f0>

In [47]:
gen

NameError: name 'gen' is not defined

In [ ]:
np.fromiter(range(5),dtype=int)

In [48]:
np.fromstring('1 2 3 4 4',sep=' ',dtype= int)

array([1, 2, 3, 4, 4])

In [49]:
np.fromstring('1,2,3,4,5,6',sep=',',dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [50]:
l=[2,345,6,57,7]

In [51]:
arr=np.array(l)

# 

In [52]:
arr1=np.array([[1,2,3,4],[5,356,74,2],[3,5,7,34]])

In [53]:
type(arr)

numpy.ndarray

In [54]:
arr1.ndim

2

In [55]:
arr1

array([[  1,   2,   3,   4],
       [  5, 356,  74,   2],
       [  3,   5,   7,  34]])

In [56]:
arr1.size

12

In [57]:
arr1.shape

(3, 4)

In [58]:
arr1.dtype

dtype('int64')

In [59]:
arr

array([  2, 345,   6,  57,   7])

In [60]:
arr.size

5

In [61]:
arr.ndim

1

In [62]:
arr.shape

(5,)

In [63]:
arr2= np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [64]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [65]:
arr2.size

16

In [66]:
arr2.ndim

3

In [67]:
arr2.shape

(2, 2, 4)

In [68]:
arr4= np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [69]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [70]:
arr4.ndim

4

In [71]:
arr4.shape

(1, 4, 2, 4)

In [72]:
range(5)

range(0, 5)

In [73]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [74]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [75]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [76]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

In [78]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [80]:
np.ones(4)

array([1., 1., 1., 1.])

In [81]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [82]:
np.empty((3,4)) #random data

array([[-2.68156159e+154, -2.68156159e+154,  3.45845952e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -2.68156159e+154,
        -2.68156159e+154],
       [ 1.97626258e-323,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]])

In [83]:
np.eye(3) #Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.linspace(2,4,4, endpoint= False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [85]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [86]:
 np.logspace([2,3],4,axis = 1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [87]:
 np.logspace([2],[3],axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [88]:
d= np.linspace(4,7,40)

In [89]:
d.ndim

1

In [90]:
d.shape

(40,)

In [91]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [92]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [94]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [96]:
np.random.rand(3)# random 3 data

array([0.14668857, 0.94130333, 0.34716354])

In [98]:
np.random.randn(5)

array([-0.87934053,  0.11180234,  1.34958777, -0.11087561,  0.43046215])

In [99]:
np.random.randn(2,3)

array([[-0.79608344,  2.06322414, -1.49544735],
       [ 0.07961424,  1.42682092, -0.84375821]])

In [102]:
np.random.randint(5,60)

34

In [103]:
arr = np.random.randint(3,9, (3,3))

In [104]:
arr

array([[8, 8, 7],
       [5, 4, 5],
       [6, 3, 4]])

In [105]:
arr.reshape(1,9)

array([[8, 8, 7, 5, 4, 5, 6, 3, 4]])

In [106]:
arr.reshape(9,1)

array([[8],
       [8],
       [7],
       [5],
       [4],
       [5],
       [6],
       [3],
       [4]])

In [107]:
arr.reshape(1,1,9)

array([[[8, 8, 7, 5, 4, 5, 6, 3, 4]]])

In [108]:
arr.reshape(3,3,1)

array([[[8],
        [8],
        [7]],

       [[5],
        [4],
        [5]],

       [[6],
        [3],
        [4]]])

In [109]:
arr.reshape(3,-1)

array([[8, 8, 7],
       [5, 4, 5],
       [6, 3, 4]])

In [110]:
arr.reshape(1,-13656)

array([[8, 8, 7, 5, 4, 5, 6, 3, 4]])

In [111]:
arr.max()

8

In [112]:
arr.min()

3

In [116]:
arr = np.random.randint(4,100,(5,5))

In [118]:
arr

array([[94, 55, 38, 86, 18],
       [62, 54, 39,  8, 90],
       [26, 45, 46, 23, 22],
       [26, 94, 25, 19, 54],
       [34, 14, 93, 20, 55]])

In [119]:
arr[3:,3:]

array([[19, 54],
       [20, 55]])

In [120]:
arr[:,[1,3]]

array([[55, 86],
       [54,  8],
       [45, 23],
       [94, 19],
       [14, 20]])

In [121]:
arr

array([[94, 55, 38, 86, 18],
       [62, 54, 39,  8, 90],
       [26, 45, 46, 23, 22],
       [26, 94, 25, 19, 54],
       [34, 14, 93, 20, 55]])

In [122]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [123]:
arr[arr>10]

array([94, 55, 38, 86, 18, 62, 54, 39, 90, 26, 45, 46, 23, 22, 26, 94, 25,
       19, 54, 34, 14, 93, 20, 55])

In [126]:
arr>50

array([[ True,  True, False,  True, False],
       [ True,  True, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [False, False,  True, False,  True]])

In [125]:
arr

array([[94, 55, 38, 86, 18],
       [62, 54, 39,  8, 90],
       [26, 45, 46, 23, 22],
       [26, 94, 25, 19, 54],
       [34, 14, 93, 20, 55]])

In [127]:
arr*arr

array([[8836, 3025, 1444, 7396,  324],
       [3844, 2916, 1521,   64, 8100],
       [ 676, 2025, 2116,  529,  484],
       [ 676, 8836,  625,  361, 2916],
       [1156,  196, 8649,  400, 3025]])

In [138]:
arr1=np.random.randint(2,3,size=(3,3))

In [139]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [140]:
arr2=np.random.randint(2,4,(3,3))

In [141]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [142]:
arr2

array([[3, 3, 3],
       [3, 2, 2],
       [3, 2, 3]])

In [143]:
arr1*arr2 # element by element multiplication

array([[6, 6, 6],
       [6, 4, 4],
       [6, 4, 6]])

In [144]:
arr1@arr2  # Matrix multiplication

array([[18, 14, 16],
       [18, 14, 16],
       [18, 14, 16]])

In [145]:
arr/0

/var/folders/z3/3z1nzc5j04bfv5b365gtfgm40000gn/T/ipykernel_24909/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [146]:
arr**2

array([[8836, 3025, 1444, 7396,  324],
       [3844, 2916, 1521,   64, 8100],
       [ 676, 2025, 2116,  529,  484],
       [ 676, 8836,  625,  361, 2916],
       [1156,  196, 8649,  400, 3025]])

In [148]:
arr= np.zeros((3,4))

In [149]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
a = np.array([1,2,3,4])

In [151]:
a

array([1, 2, 3, 4])

In [152]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
b=np.array([5,6,7])

In [154]:
b

array([5, 6, 7])

In [161]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [159]:
b.size

3

In [160]:
b.shape

(3,)

In [162]:
b

array([5, 6, 7])

In [163]:
b.T

array([5, 6, 7])

In [164]:
b=np.array([[5,6,7]])

In [165]:
b

array([[5, 6, 7]])

In [167]:
b.T+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [168]:
arr= np.random.rand(5,4)

In [169]:
arr

array([[0.53083232, 0.08932109, 0.28565771, 0.4674192 ],
       [0.76522924, 0.83284021, 0.89613879, 0.0267291 ],
       [0.4921728 , 0.13493617, 0.46227472, 0.85826511],
       [0.96170664, 0.50139768, 0.83152917, 0.04218102],
       [0.96834929, 0.943289  , 0.75544817, 0.58690322]])

In [170]:
np.sqrt(arr)

array([[0.72858241, 0.29886634, 0.53446955, 0.68368062],
       [0.87477382, 0.9126008 , 0.94664607, 0.16349037],
       [0.70155028, 0.3673366 , 0.67990787, 0.92642599],
       [0.98066643, 0.7080944 , 0.91188221, 0.20538018],
       [0.9840474 , 0.97123066, 0.86916522, 0.76609609]])

In [171]:
np.exp(arr)

array([[1.70034695, 1.09343169, 1.33063691, 1.59587025],
       [2.14948708, 2.29984151, 2.45012437, 1.02708953],
       [1.63586678, 1.14446374, 1.58768141, 2.35906443],
       [2.61615751, 1.65102727, 2.2968283 , 1.04308328],
       [2.63359357, 2.56841505, 2.12856528, 1.79841051]])

In [172]:
np.log10(arr)

array([[-0.27504264, -1.04904598, -0.54415406, -0.33029346],
       [-0.11620844, -0.07943831, -0.04762473, -1.57301564],
       [-0.30788239, -0.86987161, -0.33509986, -0.06637854],
       [-0.01695739, -0.29981768, -0.08012251, -1.37488295],
       [-0.01396796, -0.02535523, -0.12179532, -0.2314335 ]])

In [174]:
arr1=np.random.randint(2,5,(5,5))

In [177]:
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.30103   , 0.30103   , 0.47712125],
       [0.60205999, 0.47712125, 0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.60205999, 0.47712125, 0.47712125, 0.30103   ],
       [0.30103   , 0.60205999, 0.47712125, 0.60205999, 0.30103   ],
       [0.30103   , 0.60205999, 0.47712125, 0.30103   , 0.30103   ]])

In [178]:
arr1

array([[3, 4, 2, 2, 3],
       [4, 3, 2, 3, 3],
       [3, 4, 3, 3, 2],
       [2, 4, 3, 4, 2],
       [2, 4, 3, 2, 2]])

In [179]:
np.random.seed(13)

In [189]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])